<?php
$_cartQty = $this->getSummaryCount();
$_webMiniCartUrl = Mage::getBaseUrl();
?>
<div id ="mini_cart_block">
    <div class="block-cart mini_cart_ajax">
            <div class="block-cart">
                <?php $_cartQty = $this->getSummaryCount() ?>
                <div class="cart-mini-title">
                    <a class="shopping-cart hidden-xs" href="<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>">
                    <span class="cart-count">
                        <?php
                        if($_cartQty<1) {
                            echo $this->__('Tom varukorg');
                        } else {
                            echo Mage::helper('checkout')->formatPrice($this->getSubtotal());
                        } ?></span>
					</a>
                </div>
                <div class="top-cart-content">
                    <?php $_items = $this->getRecentItems() ?>
                    <?php if (count($_items)): ?>
                        <ol id="cart-sidebar" class="mini-products-list">
                            <?php foreach ($_items as $_item): ?>
                                <?php echo $this->getItemHtml($_item) ?>
                            <?php endforeach; ?>
                        </ol>
                        <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
                        <script type="text/javascript">
                            jQuery(document).ready(function ($j) {
                                /*
                                * add or reduce quanity of product in minicart.
                                */
                                $j("#cart-sidebar .item").each(function(){
                                    var $itemBox = $j(this).children(".product-details");
                                    var $qtyBox = $j(this).find(".product-qty");
                                    return;//edit by jerry
                                    var item_id = $itemBox.find(".btn-edit").attr("href").split("/id/")[1].split("/")[0];
                                    var item_qty;
                                    $itemBox.find(".qtyBtn").click(function(){
                                        if($j(this).hasClass("qtyAdd")){
                                            ajaxMiniCart(item_id,item_qty);
                                            //after ajax
                                            item_qty = parseInt($qtyBox.text())+1;
                                            $qtyBox.text(item_qty);
                                        }else if($j(this).hasClass("qtyReduce")){
                                            item_qty = parseInt($qtyBox.text());
                                            if(item_qty <= 1){
                                                //when qty <= 1 , show remove message
                                                $itemBox.find(".btn-remove").click();
                                            }else if(item_qty>1){
                                                ajaxMiniCart(item_id,item_qty);
                                                //after ajax
                                                item_qty -=1;
                                                $qtyBox.text(item_qty);
                                            }
                                        }
                                    });
                                });
                                /*
                                * ajaxMiniCart
                                * product_id,qty,method('update')
                                * */
                                function ajaxMiniCart(id, itemqty){
                                    if($j.ajax){
                                        $j.ajax({
                                            type:'post',
                                            async:true,
                                            url:'<?php echo $_webMiniCartUrl.'/mivec/checkout/cart/update.php'?>',
                                            data:{product_id:id,qty:itemqty,method:'update'},
                                            dataType:'json',
                                            beforeSend: function(){ loadingAjaxcart(true);//show loading
                                            },
                                            success:function (data) {
                                                loadingAjaxcart(false);//hide loading
                                            },
                                            complete: function(XMLHttpRequest, textStatus) {
                                                sumMiniCart();
                                                showBoxInfo('<div class ="ajaxcartReponse"><p class ="info">Your cart has been updated</p></div>');
                                            },
                                            error: function(){
                                                confirm('Find error in updating cart!');
                                            }
                                        });
                                    }
                                }
                                function sumMiniCart() {
                                    var sumItem = 0;
                                    $j.each($j("#cart-sidebar li"),function(){
                                        sumItem += (parseInt($j(this).find(".product-qty").text()))*($j(this).find(".price").text().split("kr")[0].replace(',','.'));
                                    });
                                    $j(".cart-mini-title .cart-count").text(sumItem.toFixed(2)+ 'kr');
                                }
                            });
                        </script>
                    <?php else: ?>
                        <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
                    <?php endif ?>
                    <div class="top-subtotal"><?php echo $this->__('Subtotal') ?>: <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?></div>
                    <?php if ($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                        <div class="actions clearfix">
                            <?php echo $this->getChildHtml('extra_actions') ?>
                            <a href="<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>" class="left action_cart">View shopping Cart</a>
                            <button type="button" title="<?php echo $this->__('Checkout') ?>" class="button right" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
                        </div>
                    <?php else:?>
                        <div class="actions clearfix">
                            <p></p>
                            <?php echo $this->getChildHtml('extra_actions') ?>
                            <a href="<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>" class="left action_cart">View shopping Cart</a>
                        </div>
                    <?php endif ?>
                </div>
            </div>
    </div>
</div>
<script type="text/javascript">
    var ajaxCartCfg = {
        'removeConfirm' : '<?php echo $this-> __('Är du säker på att du vill ta bort denna produkt från varukorgen?') ?>',
    };
</script>