<!--nav-vcontainer-->
<div class="nav-vcontainer hidden-xs hidden-sm">
    <div class="nav-inner">
        <div class="vmegamenu-title"><h2><i class="fa fa-bars"></i><?php echo $this->__(' Produkter ') ?></h2></div>
        <div class="vmegamenu-contain">
            <div id="nav_vmegamenu" class="nav_vmegamenu">
                <?php $megamenu =  $this->getLayout()->createBlock('megamenu/megamenu'); ?>
                <?php echo $megamenu->drawMegamenuMain(); ?>
            </div>
        </div>
        <div id="vmegamenu-background"></div>
        <div id="vmegamenu-mask"></div>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        var MEGAMENU_EFFECT = <?php echo (int)Mage::getStoreConfig('megamenu/general/effect')?>;
        //]]>
    </script>
	<script type="text/javascript">
        //add by jerry
        /*
         *set .dropdown top
         */
        ;jQuery(document).ready(function($){
            $(".nav-container-box .nav-vcontainer").hover(function () {
                $(".nav-vcontainer .vmegamenu-title").addClass("hover");
            },function () {
                $(".nav-vcontainer .vmegamenu-title").removeClass("hover");
            });
            $("#vmegamenu-background").css('height',(40*$(".header-wrapper #nav_vmegamenu>div").length)+'px');
            (function(){
                jQuery(".vmegamenu-contain .megamenu").each(function(){
                    var tmpMindex = $(this).index();
                    var tmpHeight = 40;
                    $(this).find(".dropdown").css('top',-tmpMindex*tmpHeight+'px');
                });
            })();
        });
        /*
         *get back height
         */
        jQuery(document).ready(function($){
            $("#nav_vmegamenu .megamenu").find(".dropdown").removeClass("dropdownShow").addClass("dropdownHide");
            $("#nav_vmegamenu").mouseout(function(){
                $("#nav_vmegamenu .megamenu").find(".dropdownShow").addClass("dropdownHide").removeClass("dropdownShow");
                $("#vmegamenu-background").css('height',(40*$("#nav_vmegamenu>div").length)+'px');//init
            });
            get_back_Height();
            function get_back_Height(){
                var tmpH1 = $(".vmegamenu-contain").height();
                jQuery(".dropdown").css("min-height",tmpH1+'px');
                var tmpH2 = 0;
                $("#nav_vmegamenu").on("mouseover",".megamenu",function(){
                    var tmpIndex = $(this).index();
                    //set other dropdown css display:none;
                    $("#nav_vmegamenu .megamenu").eq(tmpIndex).find(".dropdown").removeClass("dropdownHide").addClass("dropdownShow").end()
                        .siblings().find(".dropdown").addClass("dropdownHide").removeClass("dropdownShow");
                    tmpH2 = $(".dropdownShow").height();
                    var tmpHeight = tmpH1>tmpH2?tmpH1:tmpH2;
                    $("#vmegamenu-background").css('height',(tmpHeight+1)+'px');
                });
            }
        });
        /*
         *set back,mask left,width
         */
        jQuery(document).ready(function($){
            set_back_left_width();
            $(window).resize(function () {
                set_back_left_width();
            });
            function set_back_left_width(){
                var tmp_vmegameny_width = $(document).width();//May IE show the bug
                var tmp_vmegameny_left = -$(".nav-vcontainer").offset().left;
                jQuery("#vmegamenu-background,#vmegamenu-mask").css({'left':tmp_vmegameny_left+'px','width':tmp_vmegameny_width+'px'});
            }
        });
        jQuery(document).ready(function($){
            /*
             *set viewmore
             */
            $('.itemMenu.level2>div.itemSubMenu.level2').remove();
            $('.newMenuBox').each(function(){
                var $itemMenu1 = $(this);
                var countA = $itemMenu1.find(".itemMenuName.level1").length;
                for(var i = 0;i<countA;i++){
                    setHref(i);
                }
                function setHref(count){
                    var len = $itemMenu1.children(".itemSubMenu.level1").eq(count).find(".itemMenu.level2>a").length;
                    //get url and add to view more
                    if(len>=8){
                        var tmpHref = $itemMenu1.find("a.itemMenuName.level1").eq(count).attr("href");
                        if($itemMenu1.find(".itemMenu.level2").eq(count).find(".viewmore").length<1)
                        $itemMenu1.find(".itemMenu.level2").eq(count).append("<p><a class='viewmore' href='"+tmpHref+"'>view more</a></p>");
                    }
                }
            });
            /*
             *set menu item hide
             */
            $(".itemSubMenu").each(function(){
                $(this).find(".itemMenu>a.itemMenuName:gt(7)").css({'display':'none'}).remove();
            });
            /**
             * add itemSubMenu for '.newMenuBox' that not have Corresponding 'div'
             * */
            $(".newMenuBox").each(function () {
                if($(this).find("div.itemSubMenu.level1").length<1){
                    $(this).append('<div class="itemSubMenu level1 newAdd"></div>');
                }
            });
            $('.itemMenu.level1').each(function(){
                return false;
                var $el= $(this);
                var $a = $el.find(".itemMenuName.level1");
                var a_len = $a.length;
                var $div = $el.find(".itemSubMenu.level1");
                var div_len = $div.length;
               if(div_len < a_len && a_len === 2){
                   if(div_len === 0){
                       $a.after('<div class="itemSubMenu level1 newAdd"></div>'); //success
                   }else if(div_len === 1){
                       var t_index = $div.index();
                       if(t_index === 1){
                           $a.eq(1).after('<div class="itemSubMenu level1 newAdd"></div>');
                       }else if(t_index === 2){
                           $a.eq(0).after('<div class="itemSubMenu level1 newAdd"></div>');
                       }
                   }
               }
               if(div_len < a_len && a_len === 1){
                   $a.after('<div class="itemSubMenu level1 newAdd"></div>');
               }
            });
        });
	</script>
</div>
