<style>
    /*.vmegamenu-banner{position: relative;}
    .vmegamenu-menu{position: fixed;z-index: 1002;top:60px;left:0;}*/
</style>
<section class="vmegamenu-banner">
	<!--edit by jerry,banner-box -->
	<div class="container-fluid banner-box">
		<div class="position position2">
            <?php $block =$this->getLayout()->createBlock('imageslider/slider')
                            ->setTemplate('themevast/imageslider/imageslider.phtml');
                            echo $block->toHtml();
                    ?>
        </div>
	</div>
</section>